name: Lint

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint

